spring:
  jpa:
    # verify transmission query
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # execute data.sql after create table
    defer-datasource-initialization: true